github-org-name: nyu-software-engineering
baseurl: /course-materials
title: Software Engineering
description: >
  A fantastic voyage through an engineering approach to the problem of software development
copyright: GNU General Public License, Version 3
layouts_dir: theme/_layouts/
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
defaults:
  - scope:
      path: "content"
      type: pages
    values:
      layout: github
  - scope:
      path: "slides"
      type: pages
    values:
      layout: presentation
